# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b169442df95d920cdcb3f2592a1210062765958a92049395f656f74c5559fd7d00f66c9f5a2b2308b51a8d2b39d94a4f4ba7908d8fcc7e4af0eac7c7643dc1e0

test:
  secret_key_base: 5d1060df3a3cd5ea0ab5bc596fc9b37382986764b8dba985da4a952c2320af7b0b31c5d4d59046df11d735e4cbdd0aca4d10fd10aa21329f98c4e11bc469f5fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
